version: '2.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3131:80
    networks:
      bicycle-network:
        aliases:
          - frontend
    environment:
      - "NODE_PATH=./src"
      - "REACT_APP_BICYCLE_API=localhost:8000/bicycle"
      - "REACT_APP_ADD_BASKET_API=localhost:8000/user/add_basket"
      - "REACT_APP_DEL_BASKET_API=localhost:8000/user/del_basket"
      - "REACT_APP_BASKET_BICYCLE_API=localhost:8000/user/basket_bicycle"
    volumes:
      - ./frontend:/app

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      bicycle-network:
        aliases:
          - webapp
    environment:
      APP_MODULE: "main:app"
      DATABASE_URL: sqlite:///./test.db

    volumes:
      - ./webapp:/app

networks:
  bicycle-network:
    external: false