version: '2.3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3131:80
    networks:
      bicycle-network:
        aliases:
          - frontend
    environment:
      NODE_PATH: ./src
      REACT_APP_BICYCLE_API: localhost/bicycle
    volumes:
      - ./frontend:/app

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      bicycle-network:
        aliases:
          - webapp
    environment:
      APP_MODULE: "main:app"

    volumes:
      - ./webapp:/app

networks:
  bicycle-network:
    external: false
    name: bicycle-network